#!/usr/bin/env bash
#
# aisoc_demo.sh — end-to-end deploy for the AISOC demo
#
# Walks the three Terraform phases in order, triggers the function-app
# code-deploy workflows on GitHub, runs the Foundry bootstrap scripts,
# and prints the resulting URLs.
#
# Idempotent: every step is safe to re-run. If a step fails (e.g. the
# Sentinel rule's 10-minute table-readiness poll times out on a totally
# cold deploy), fix the cause and re-run the script — completed steps
# converge to a no-op.
#
# Prereqs (one-time per machine):
#   - az login
#   - az account set -s <SUBSCRIPTION_ID>      (the sub you want everything in)
#   - terraform >= 1.6
#   - gh CLI authenticated to github.com (`gh auth login`)
#
# GitHub Actions auth: this script uses **OIDC federated credentials**,
# not a long-lived secret — see the "OIDC bootstrap" step below. No
# `AZURE_CREDENTIALS` secret needed; the deploy works fine when the
# repo is public.
#
# Usage:
#   ./aisoc_demo.sh deploy   [--key=value]...
#   ./aisoc_demo.sh destroy  [--key=value]...
#   ./aisoc_demo.sh --help
#
# The first argument is a subcommand:
#   deploy   — walk Phases 1 → 2 → 3 (build, configure, smoke-test)
#   destroy  — terraform destroy in reverse order (3 → 2 → 1)
#
# Configuration precedence (low → high):
#   1. variables.tf defaults inside each phase
#   2. ./aisoc.config (gitignored) — copy from aisoc.config.example
#   3. --flag=value on the CLI
#   4. Pre-set TF_VAR_* in the current shell (always wins)
#
# Any --key=value is forwarded as TF_VAR_<key> across all phases.
# Terraform silently ignores TF_VAR_<x> if x isn't declared in that
# phase's module, so a Phase-1-only var (e.g. --vm-size=...) won't
# bleed into Phase 2/3.
#
# To re-deploy a single phase, run terraform apply directly inside that
# phase's directory — null_resources will re-run the configure scripts.

set -euo pipefail

REPO="ErikVabu-Personal/aisoc-lab"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# ── Output helpers ───────────────────────────────────────────────────
NC=$'\033[0m'; CYAN=$'\033[36m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; BOLD=$'\033[1m'; BLUE=$'\033[34m'
say()  { printf '\n%s%s==> %s%s\n' "$BOLD" "$CYAN" "$*" "$NC"; }
ok()   { printf '%sOK: %s%s\n' "$GREEN" "$*" "$NC"; }
warn() { printf '%sWARN: %s%s\n' "$YELLOW" "$*" "$NC" >&2; }
die()  { printf '%sERROR: %s%s\n' "$RED" "$*" "$NC" >&2; exit 1; }

# ── Banner ──────────────────────────────────────────────────────────
# Pixel-art cruise ship + title, in NVISO blue.
print_banner() {
  printf '\n'
  printf '%s' "$CYAN"
  cat <<'BANNER'
                       ____         ____
                      |____|       |____|
                 _____|_|_|_________|_|_|_____
                |____________________________|
            ____|____________________________|____
           |_______________________________________|
            \_____________________________________/
BANNER
  printf '%s' "$BLUE"
  cat <<'BANNER'
             ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
BANNER
  printf '%s\n' "$NC"
  printf '%s%s          N V I S O   C r u i s e s%s\n' "$BOLD" "$CYAN" "$NC"
  printf '%s          Agentic SOC Demo%s\n\n' "$CYAN" "$NC"
}
print_banner

# ── Argument parsing ─────────────────────────────────────────────────
usage() {
  cat <<'EOF'
Usage: ./aisoc_demo.sh <command> [options]

Commands:
  deploy    Walk Phases 1 → 2 → 3 — Terraform applies, function-app
            code workflows, Foundry bootstrap, smoke-test print.
            Idempotent; safe to re-run.
  destroy   Tear down all phases (Phase 3 → 2 → 1) via terraform
            destroy. Leaves the OIDC trust and AZURE_* repo
            variables in place so the next `deploy` is one command.
            5-second countdown before applying.

Common Terraform variables:
  --resource-group=...    Resource group to create / use in Azure
                          (default: rg-sentinel-test). Phase 1 creates
                          the RG with this name; Phases 2 & 3 deploy
                          into it.
  --azure-location=...    Azure region for Sentinel + lab VM
                          (default: westus). Phase 2 deploys to
                          westcentralus by default — those two
                          together are the empirically-validated
                          combo for new subs whose other regions
                          have zero App Service / EP-series quota.
  --location-override=... Region for Phase 2 (App Service / Function
                          Apps). Default: westcentralus.
  --foundry-location=...  Region for Foundry hub/project/model
                          (default: eastus2 — Model Router is
                          region-gated to East US 2 / Sweden Central).
  --vm-size=...           Lab VM size (default: Standard_D2s_v3)

  (Lab VM admin password is auto-generated by Terraform — printed
   at the end of the run. It's stored in Terraform state and stays
   stable across re-applies. To force your own value, pre-set
   TF_VAR_admin_password in the env.

   RDP is open from any source — this is a throwaway test box.)

Common Terraform variables (Phase 2):
  --location-override=...     Region for Function Apps (default: westcentralus)
  --foundry-location=...      Region for Foundry hub/project (default: eastus2)
  --foundry-model-choice=...  Model name (default: gpt-4.1-mini)
  --runner-image=...          Override runner image tag (default: :latest)

Other:
  --subscription=...          Azure subscription to deploy into
                              (defaults to current `az account show` selection)
  --skip-oidc-bootstrap       Skip the GitHub→Azure federated-credential setup
                              (use if you've already bootstrapped or are
                              re-running from a fresh shell). Only meaningful
                              for the `deploy` command.
  -h, --help                  show this help

Config file:
  ./aisoc.config (gitignored, optional). Sourced before CLI parsing so
  it acts as your baseline; --flag values override for the current run.
  Copy ./aisoc.config.example to get started — everything documented
  there: RG, regions, VM password, Foundry model, demo user roster, etc.

Generic pass-through:
  Any unrecognized --key=value is forwarded as TF_VAR_<key>=<value>.
  Dashes in <key> are converted to underscores (--foo-bar -> TF_VAR_foo_bar).

Sensitive values:
  For passwords / API keys, prefer pre-setting TF_VAR_<name> in the
  environment so the value never lands in shell history or process
  listings. Pre-set env vars take precedence over --flag values.

Examples:
  # Minimal first-time deploy (admin password auto-generated):
  ./aisoc_demo.sh deploy \
      --resource-group=rg-aisoc-demo --azure-location=westus

  # Override Foundry region:
  ./aisoc_demo.sh deploy \
      --resource-group=rg-aisoc-demo \
      --azure-location=westus --foundry-location=swedencentral

  # Tear it all down:
  ./aisoc_demo.sh destroy
EOF
}

declare -A USER_VARS=()
SUBSCRIPTION_OVERRIDE=""
SKIP_OIDC=0
ACTION=""

# Snapshot which TF_VAR_* the operator had set in their shell BEFORE
# this script ran, AND what value each one held. These are the
# highest-precedence values: nothing CLI or aisoc.config can override
# them. The classic pattern is:
#
#   TF_VAR_admin_password=xxx ./aisoc_demo.sh deploy --resource-group=rg
#
# where the password is set in the shell (kept out of CLI history /
# aisoc.config) and the CLI sets the rest.
#
# Why we capture VALUES not just names: aisoc.config below uses
# `source`, which lets a `TF_VAR_x=...` line in the file silently
# overwrite the shell-preset value. After sourcing we restore the
# snapshotted values, so the shell wins regardless of what
# aisoc.config tries to do.
declare -A PRE_SHELL_TF_VARS=()
while IFS='=' read -r _name _value; do
  if [[ "$_name" == TF_VAR_* ]]; then
    PRE_SHELL_TF_VARS["$_name"]="$_value"
  fi
done < <(env)
unset _name _value

# Source aisoc.config (gitignored) if present, so the user can keep
# their TF_VAR_* + AISOC_* defaults in one place at the repo root
# instead of scattered tfvars files. CLI flags parsed below override
# these values for the current run; pre-shell env vars (snapshot
# above) still win over both.
if [[ -f "$ROOT/aisoc.config" ]]; then
  # shellcheck disable=SC1091
  source "$ROOT/aisoc.config"
  echo "Loaded $ROOT/aisoc.config" >&2
fi

# Restore shell-preset TF_VAR_* values that aisoc.config might have
# clobbered during `source`. After this, anything left in the env is
# either shell-preset (= the snapshotted value) or aisoc.config-set
# (= up for grabs by the CLI loop below).
for _name in "${!PRE_SHELL_TF_VARS[@]}"; do
  export "$_name=${PRE_SHELL_TF_VARS[$_name]}"
done
unset _name
# aisoc.config can set its own deploy-script-level knobs:
#   AISOC_SKIP_OIDC=1                 -> skip OIDC bootstrap
#   AISOC_GITHUB_REPO=<owner>/<repo>  -> override the GitHub repo
#   AZURE_SUBSCRIPTION_OVERRIDE=<id>  -> switch subscription
[[ "${AISOC_SKIP_OIDC:-0}" == "1" ]] && SKIP_OIDC=1
[[ -n "${AISOC_GITHUB_REPO:-}" ]] && REPO="$AISOC_GITHUB_REPO"
[[ -n "${AZURE_SUBSCRIPTION_OVERRIDE:-}" ]] && SUBSCRIPTION_OVERRIDE="$AZURE_SUBSCRIPTION_OVERRIDE"

# First positional arg is the subcommand: deploy or destroy.
# Allow --help / -h before the subcommand for convenience.
if [[ $# -ge 1 ]]; then
  case "$1" in
    deploy|destroy)  ACTION="$1"; shift ;;
    -h|--help)       usage; exit 0 ;;
    *)               die "first argument must be 'deploy' or 'destroy' (got: '$1'). Try --help." ;;
  esac
fi
[[ -z "$ACTION" ]] && { usage >&2; exit 2; }

# Convert --foo-bar to TF_VAR_foo_bar
add_var() {
  local key="$1" value="$2"
  local tf_name
  tf_name="$(echo "$key" | tr '-' '_')"
  USER_VARS["$tf_name"]="$value"
}

# Friendly alias: --resource-group=<name> maps to Phase 1's variable
# `resource_group_name`. Phase 1 creates the RG with that name;
# Phases 2 and 3 inherit it via Phase 1's remote-state output.
set_resource_group() {
  USER_VARS["resource_group_name"]="$1"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)              usage; exit 0 ;;
    --skip-oidc-bootstrap)  SKIP_OIDC=1; shift ;;
    --subscription=*)       SUBSCRIPTION_OVERRIDE="${1#*=}"; shift ;;
    --subscription)         [[ $# -ge 2 ]] || die "missing value for --subscription"
                            SUBSCRIPTION_OVERRIDE="$2"; shift 2 ;;
    --resource-group=*)     set_resource_group "${1#*=}"; shift ;;
    --resource-group)       [[ $# -ge 2 ]] || die "missing value for --resource-group"
                            set_resource_group "$2"; shift 2 ;;
    --*=*)
      pair="${1#--}"; key="${pair%%=*}"; value="${pair#*=}"
      add_var "$key" "$value"
      shift
      ;;
    --*)
      key="${1#--}"
      [[ $# -ge 2 ]] || die "missing value for --$key (try --help)"
      add_var "$key" "$2"
      shift 2
      ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
done

# Export each CLI-supplied value as TF_VAR_<name>. Precedence:
#   1. (highest) Pre-shell env vars — captured in PRE_SHELL_TF_VARS
#      above. We never clobber these so sensitive values can stay
#      out of CLI history / aisoc.config.
#   2. CLI flags — override aisoc.config (this loop).
#   3. (lowest) aisoc.config — applied via `source` above.
#
# Anything in the env that's NOT in PRE_SHELL_TF_VARS came from
# sourcing aisoc.config — those should yield to the CLI value. The
# bare `${!envvar:-}` check we used to do conflated the two,
# accidentally letting aisoc.config beat the CLI.
for k in "${!USER_VARS[@]}"; do
  envvar="TF_VAR_$k"
  if [[ -n "${PRE_SHELL_TF_VARS[$envvar]:-}" ]]; then
    continue  # operator's shell wins
  fi
  export "$envvar=${USER_VARS[$k]}"
done

# Optional subscription switch (must happen before any az/terraform calls).
if [[ -n "$SUBSCRIPTION_OVERRIDE" ]]; then
  az account set -s "$SUBSCRIPTION_OVERRIDE"
fi

# ── 0) Prereq checks ─────────────────────────────────────────────────
say "Checking prerequisites"

command -v az        >/dev/null 2>&1 || die "az CLI not found"
command -v terraform >/dev/null 2>&1 || die "terraform not found (need >= 1.6)"
command -v gh        >/dev/null 2>&1 || die "gh CLI not found"
command -v jq        >/dev/null 2>&1 || die "jq not found (used by Phase 1 Sentinel-rule deploy)"

az account show >/dev/null 2>&1 || die "az not logged in. Run: az login"
gh auth status -h github.com >/dev/null 2>&1 || die "gh not authenticated. Run: gh auth login"

ok "prereqs satisfied"

# ── DESTROY mode ─────────────────────────────────────────────────────
# Tear down the lab in reverse order. We don't touch the OIDC trust
# (federated cred + repo vars) — those are stateless config a re-deploy
# would just re-write, and keeping them lets the next deploy be a
# one-liner.
if [[ "$ACTION" == "destroy" ]]; then
  warn "DESTROY mode: about to run \`terraform destroy\` in Phase 3, then 2, then 1."
  warn "All Azure resources created by the demo will be removed."
  warn "Press Ctrl-C now to abort. Continuing in 5 seconds..."
  sleep 5

  destroy_phase() {
    local dir="$1"
    say "Destroying: $dir"
    if [[ ! -d "$dir/.terraform" ]]; then
      warn "$dir is not initialized (.terraform/ missing) — skipping"
      return 0
    fi
    # init -upgrade reconciles the lock file in case providers were
    # added since the last apply (e.g. we added null_resource blocks
    # which require hashicorp/null). Without this, destroy fails with
    # "Inconsistent dependency lock file".
    ( cd "$dir" && terraform init -upgrade -input=false && terraform destroy -auto-approve -input=false )
  }

  # Foundry hub (Microsoft.CognitiveServices/accounts) can't be deleted
  # while it has child projects. The project is created out-of-band by
  # deploy_foundry_project.sh, so Terraform doesn't manage it. Delete
  # it via ARM before terraform destroy reaches the hub.
  pre_destroy_phase2_cleanup() {
    local sub rg hub proj
    sub="$( cd terraform/2-deploy-aisoc && terraform output -raw subscription_id 2>/dev/null || true )"
    rg="$(  cd terraform/2-deploy-aisoc && terraform output -raw resource_group   2>/dev/null || true )"
    hub="$( cd terraform/2-deploy-aisoc && terraform output -raw foundry_hub_name 2>/dev/null || true )"
    proj="$(cd terraform/2-deploy-aisoc && terraform output -raw foundry_project_name 2>/dev/null || true )"

    if [[ -z "$sub" || -z "$rg" || -z "$hub" || -z "$proj" ]]; then
      warn "Couldn't resolve Foundry hub/project from terraform output — skipping pre-destroy project cleanup."
      warn "If the destroy fails with 'Cannot delete resource while nested resources exist',"
      warn "delete the project manually: az rest --method delete --url '...projects/<name>?api-version=2025-06-01'"
      return 0
    fi

    local url="https://management.azure.com/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.CognitiveServices/accounts/$hub/projects/$proj?api-version=2025-06-01"
    say "Pre-destroy: removing Foundry project '$proj' (nested under hub '$hub')"
    if az rest --method delete --url "$url" --only-show-errors >/dev/null 2>&1; then
      ok "Foundry project deleted"
    else
      warn "Foundry project delete returned non-zero (may already be gone) — continuing"
    fi
  }

  # Phase 1 lab VM has an auto-shutdown schedule and runs the
  # AzureMonitorWindowsAgent extension. If the VM is deallocated when
  # `terraform destroy` reaches the extension resource, Azure rejects
  # the delete with:
  #   OperationNotAllowed: Cannot modify extensions in the VM when
  #   the VM is not running.
  # Two complementary fixes here:
  #   1. Try `az vm start` first — wakes the VM long enough for the
  #      extension teardown to succeed. Idempotent.
  #   2. If start fails (quota / region issue / VM already deleted),
  #      fall back to `terraform state rm` on each extension. Azure
  #      cleans them up automatically when the VM itself is deleted,
  #      so removing them from state lets the rest of the destroy
  #      proceed.
  pre_destroy_phase1_cleanup() {
    local p1=terraform/1-deploy-sentinel
    if [[ ! -d "$p1/.terraform" ]]; then
      return 0  # nothing to do
    fi

    local rg vm
    rg="$( cd "$p1" && terraform output -raw resource_group 2>/dev/null || true )"
    vm="$( cd "$p1" && terraform output -json 2>/dev/null \
            | python3 -c 'import sys,json; d=json.load(sys.stdin); print((d.get("vm_name") or {}).get("value") or "")' \
            2>/dev/null || true )"
    # Phase 1's main.tf default name is "win11-test" — fall back to
    # that when the output isn't exposed.
    [[ -z "$vm" ]] && vm="win11-test"

    if [[ -n "$rg" ]]; then
      say "Pre-destroy: ensuring Phase 1 VM '$vm' is running so extensions can be torn down"
      if az vm start -g "$rg" -n "$vm" --no-wait --only-show-errors >/dev/null 2>&1; then
        # --no-wait kicked off; give Azure a moment to flip state to
        # "running" so the extension delete sees a live VM. Up to
        # ~3 minutes is enough for a Windows 11 cold start; we cap
        # at 90s and fall through to the state-rm rescue if it's
        # still not up.
        local i=0
        while (( i < 18 )); do
          local ps
          ps="$(az vm get-instance-view -g "$rg" -n "$vm" \
                --query 'instanceView.statuses[?starts_with(code,`PowerState/`)].code | [0]' \
                -o tsv 2>/dev/null || true)"
          if [[ "$ps" == "PowerState/running" ]]; then
            ok "Phase 1 VM is running"
            break
          fi
          sleep 5
          i=$((i + 1))
        done
      else
        warn "az vm start failed (vm may already be deleted) — will rely on state-rm fallback if needed"
      fi
    fi

    # Belt-and-braces: even if the VM is now running, the extension
    # delete can still race on a slow region. Strip extensions from
    # state UNCONDITIONALLY when the VM is currently deallocated.
    # Costs nothing — Azure will sweep them with the VM itself.
    local ps_now
    ps_now="$(az vm get-instance-view -g "$rg" -n "$vm" \
              --query 'instanceView.statuses[?starts_with(code,`PowerState/`)].code | [0]' \
              -o tsv 2>/dev/null || true)"
    if [[ "$ps_now" != "PowerState/running" ]]; then
      warn "VM is not running — pruning extension resources from Phase 1 state so destroy doesn't trip on them"
      # Discover extension resources currently in state and pop each.
      local ext_addrs
      ext_addrs="$(cd "$p1" && terraform state list 2>/dev/null \
                   | grep -E 'azurerm_virtual_machine_extension(\.|\[)' || true)"
      if [[ -n "$ext_addrs" ]]; then
        while IFS= read -r addr; do
          [[ -z "$addr" ]] && continue
          (cd "$p1" && terraform state rm "$addr") >/dev/null 2>&1 \
            && echo "  pruned $addr" >&2 \
            || warn "  state rm failed for $addr"
        done <<< "$ext_addrs"
      fi
    fi
  }

  destroy_phase terraform/3-deploy-pixelagents-web
  pre_destroy_phase2_cleanup
  destroy_phase terraform/2-deploy-aisoc
  pre_destroy_phase1_cleanup
  destroy_phase terraform/1-deploy-sentinel

  printf '\n%s%s═════════════════════════ Demo torn down ═════════════════════════%s\n' "$BOLD" "$GREEN" "$NC"
  printf '  All three Terraform phases are destroyed.\n'
  printf '  OIDC trust + AZURE_* repo variables are preserved.\n'
  printf '  Run ./aisoc_demo.sh to redeploy when ready.\n\n'
  exit 0
fi

# ── 0a) OIDC bootstrap ───────────────────────────────────────────────
# Set up GitHub-Actions-to-Azure auth via OIDC (federated credentials),
# so the workflows never hold a long-lived secret. Idempotent: if the
# SP, federated credential, role assignment, and repo variables already
# exist this is a no-op.
OIDC_STATUS=""
if [[ "$SKIP_OIDC" == "1" ]]; then
  say "Skipping OIDC bootstrap (--skip-oidc-bootstrap)"
  SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
  TENANT_ID="$(az account show --query tenantId -o tsv)"
  OIDC_STATUS="skipped (--skip-oidc-bootstrap)"
else
say "Bootstrapping OIDC trust between GitHub and Azure"

OIDC_APP_NAME="${OIDC_APP_NAME:-aisoc-lab-gha}"
OIDC_BRANCH="${OIDC_BRANCH:-main}"
OIDC_FEDCRED_NAME="aisoc-lab-${OIDC_BRANCH}"
OIDC_SUBJECT="repo:${REPO}:ref:refs/heads/${OIDC_BRANCH}"

SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
TENANT_ID="$(az account show --query tenantId -o tsv)"

# 1. Service principal (no password — we'll attach a federated credential).
APP_ID="$(az ad app list --display-name "$OIDC_APP_NAME" --query '[0].appId' -o tsv 2>/dev/null || true)"
if [[ -z "$APP_ID" ]]; then
  echo "  creating Azure AD app '$OIDC_APP_NAME'"
  APP_ID="$(az ad app create --display-name "$OIDC_APP_NAME" --query appId -o tsv)"
  az ad sp create --id "$APP_ID" >/dev/null
else
  echo "  Azure AD app '$OIDC_APP_NAME' already exists ($APP_ID)"
  # Make sure the SP shadow exists too — it can be missing if the app was created elsewhere.
  az ad sp show --id "$APP_ID" >/dev/null 2>&1 || az ad sp create --id "$APP_ID" >/dev/null
fi
SP_OBJECT_ID="$(az ad sp show --id "$APP_ID" --query id -o tsv)"

# 2. Federated credential pinning the trust to this repo + branch.
existing_fc="$(az ad app federated-credential list --id "$APP_ID" \
                 --query "[?name=='$OIDC_FEDCRED_NAME'].name" -o tsv 2>/dev/null || true)"
if [[ -z "$existing_fc" ]]; then
  echo "  creating federated credential subject=$OIDC_SUBJECT"
  az ad app federated-credential create --id "$APP_ID" --parameters "$(cat <<EOF
{
  "name": "$OIDC_FEDCRED_NAME",
  "issuer": "https://token.actions.githubusercontent.com",
  "subject": "$OIDC_SUBJECT",
  "audiences": ["api://AzureADTokenExchange"]
}
EOF
)" >/dev/null
else
  echo "  federated credential '$OIDC_FEDCRED_NAME' already exists"
fi

# 3. Subscription-scoped Contributor (idempotent — `az role assignment create`
#    is a no-op if the assignment already exists, returns non-zero on conflict).
SCOPE="/subscriptions/$SUBSCRIPTION_ID"
echo "  ensuring Contributor role on $SCOPE"
az role assignment create \
  --assignee-object-id "$SP_OBJECT_ID" \
  --assignee-principal-type ServicePrincipal \
  --role Contributor \
  --scope "$SCOPE" \
  >/dev/null 2>&1 || true

# 4. Push the three IDs as repo variables (publicly visible — they're identifiers, not secrets).
echo "  syncing AZURE_CLIENT_ID / AZURE_TENANT_ID / AZURE_SUBSCRIPTION_ID to $REPO"
gh variable set AZURE_CLIENT_ID       --repo "$REPO" --body "$APP_ID"          >/dev/null
gh variable set AZURE_TENANT_ID       --repo "$REPO" --body "$TENANT_ID"       >/dev/null
gh variable set AZURE_SUBSCRIPTION_ID --repo "$REPO" --body "$SUBSCRIPTION_ID" >/dev/null

ok "OIDC trust ready (workflows will authenticate to subscription $SUBSCRIPTION_ID)"
OIDC_STATUS="bootstrapped (subject=$OIDC_SUBJECT)"
fi  # SKIP_OIDC

# ── Plan summary ─────────────────────────────────────────────────────
# Show the user exactly what's about to happen before any terraform
# apply runs — subscription, RG, region, model choice, etc. Values are
# resolved from CLI flags / env vars (TF_VAR_*) with the variable
# defaults from each phase's variables.tf as fallbacks.
print_plan_summary() {
  local rg="${TF_VAR_resource_group_name:-rg-sentinel-test}"
  local region="${TF_VAR_azure_location:-westus}"
  local phase2_region="${TF_VAR_location_override:-westcentralus}"
  local vm_size="${TF_VAR_vm_size:-Standard_D2s_v3}"
  local admin_user="${TF_VAR_admin_username:-azureadmin}"
  local foundry_region="${TF_VAR_foundry_location:-eastus2}"
  local foundry_model="${TF_VAR_foundry_model_choice:-gpt-4.1-mini}"
  local sub_name
  sub_name="$(az account show --query name -o tsv 2>/dev/null || echo '?')"

  printf '\n%s%s── Deploy plan ──────────────────────────────────────────────────────%s\n' "$BOLD" "$CYAN" "$NC"
  printf '  Subscription      : %s (%s)\n' "$SUBSCRIPTION_ID" "$sub_name"
  printf '  Tenant            : %s\n' "$TENANT_ID"
  printf '  Resource group    : %s   [Phase 1 will create / use]\n' "$rg"
  printf '  Phase 1 region    : %s   [Sentinel + lab VM]\n' "$region"
  printf '  Phase 2 region    : %s   [App Service / Function Apps]\n' "$phase2_region"
  printf '  VM size           : %s\n' "$vm_size"
  printf '  VM admin user     : %s   (password auto-generated)\n' "$admin_user"
  printf '  Foundry region    : %s   [hub + project + model]\n' "$foundry_region"
  printf '  Foundry model     : %s\n' "$foundry_model"
  printf '  GitHub repo       : %s\n' "$REPO"
  printf '  OIDC              : %s\n' "$OIDC_STATUS"
  printf '%s%s─────────────────────────────────────────────────────────────────────%s\n' "$BOLD" "$CYAN" "$NC"

  # Detect any per-phase tfvars files; their values silently override the
  # banner above. Call them out explicitly so users aren't surprised.
  local tfvars_files=()
  for d in terraform/1-deploy-sentinel terraform/2-deploy-aisoc terraform/3-deploy-pixelagents-web; do
    [[ -f "$d/terraform.tfvars" ]] && tfvars_files+=("$d/terraform.tfvars")
  done
  if [[ ${#tfvars_files[@]} -gt 0 ]]; then
    warn "These terraform.tfvars files exist and will OVERRIDE the values shown above:"
    for f in "${tfvars_files[@]}"; do printf '  - %s\n' "$f" >&2; done
  fi
  printf '\n'
}
print_plan_summary

apply_phase() {
  local dir="$1"
  # Vars come from (in priority order):
  #   1. Pre-set TF_VAR_* env vars and --flag args (already exported above)
  #   2. terraform.tfvars in $dir (if present — optional)
  #   3. variable defaults in the module
  ( cd "$dir" && terraform init -upgrade -input=false && terraform apply -auto-approve -input=false )
}

# Trigger a GHA workflow and wait for the resulting run to finish.
# Captures the latest run id before triggering, then waits for a NEW run
# id to appear so we don't accidentally watch a stale completed run.
trigger_and_wait_workflow() {
  local workflow="$1"
  say "Triggering workflow: $workflow"

  local before_id
  before_id="$(gh run list --workflow="$workflow" --repo "$REPO" --limit 1 \
               --json databaseId -q '.[0].databaseId // empty' 2>/dev/null || echo '')"

  gh workflow run "$workflow" --repo "$REPO"

  # Poll for ~90 s for a new run id to appear at the top of the list.
  local run_id="" deadline=$((SECONDS + 90))
  while [[ -z "$run_id" && $SECONDS -lt $deadline ]]; do
    sleep 3
    local latest
    latest="$(gh run list --workflow="$workflow" --repo "$REPO" --limit 1 \
              --json databaseId -q '.[0].databaseId // empty' 2>/dev/null || echo '')"
    if [[ -n "$latest" && "$latest" != "$before_id" ]]; then
      run_id="$latest"
    fi
  done

  [[ -z "$run_id" ]] && die "no new run appeared for $workflow after 90 s"
  echo "  watching run id: $run_id"
  gh run watch "$run_id" --repo "$REPO" --exit-status
  ok "$workflow completed"
}

# ── 1) Phase 1 — Sentinel + RG + Ship Control Panel + analytic rule ──
say "Phase 1: Sentinel + Ship Control Panel"
apply_phase terraform/1-deploy-sentinel
ok "Phase 1 applied (repo vars synced; auth-failures rule deployed)"

# ── 2) Phase 2 — Foundry, Runner, Orchestrator, SOC Gateway ──────────
say "Phase 2: Foundry + Runner + Function Apps"
apply_phase terraform/2-deploy-aisoc
ok "Phase 2 applied (Function Apps exist; runner is up; gateway key wired)"

# ── 3) Function App code deploys via GHA ─────────────────────────────
say "Deploying Function App code via GitHub Actions"
trigger_and_wait_workflow deploy-aisoc-orchestrator.yml
trigger_and_wait_workflow deploy-soc-gateway.yml
ok "Function App code deployed"

# ── 4) Foundry bootstrap (project + agents + workflow) ───────────────
say "Foundry bootstrap"
( cd terraform/2-deploy-aisoc && ./scripts/deploy_foundry_project.sh )
( cd terraform/2-deploy-aisoc && ./scripts/deploy_prompt_agents_with_runner_tools.sh )

# Foundry workflow upsert is OPTIONAL.
#
# The script POSTs to the Foundry portal's internal nextgen API
# (https://ai.azure.com/nextgen/api/query). That endpoint expects a
# portal-session token, not the AAD token `az` mints — so it fails
# with 401 "LoginRequired" when called from a CLI/CI context.
#
# Critically, NOTHING in the production pipeline consumes this
# workflow definition: the orchestrator Function App calls Foundry
# agents directly via the Responses API. The "workflow" is purely a
# portal-visualization convenience for triggering the pipeline from
# the Foundry Studio UI.
#
# So: try it, but don't fail the deploy if it doesn't take.
WORKFLOW_DEPLOY_OK=1
if ! ( cd terraform/2-deploy-aisoc && ./scripts/deploy_foundry_workflow.sh ); then
  WORKFLOW_DEPLOY_OK=0
  warn "Foundry workflow upsert failed (portal nextgen API rejected the CLI token)."
  warn "This step is OPTIONAL — the orchestrator runs without a registered Foundry workflow."
  warn "If you want the workflow visible in Foundry Studio, deploy"
  warn "  terraform/2-deploy-aisoc/workflows/aisoc-incident-pipeline.yaml"
  warn "manually via the portal (Workflows → Import YAML)."
fi

if [[ "$WORKFLOW_DEPLOY_OK" == "1" ]]; then
  ok "Foundry project + agents + workflow seeded"
else
  ok "Foundry project + agents seeded (workflow registration skipped — see warning above)"
fi

# ── 5) Phase 3 — PixelAgents Web ─────────────────────────────────────
say "Phase 3: PixelAgents Web"
apply_phase terraform/3-deploy-pixelagents-web
ok "Phase 3 applied (runner + orchestrator wired with PIXELAGENTS_URL/TOKEN)"

# ── 6) Completion summary ────────────────────────────────────────────
PIXEL_URL="$(cd terraform/3-deploy-pixelagents-web && terraform output -raw pixelagents_url)"
SHIPCP_URL="$(cd terraform/1-deploy-sentinel && terraform output -raw ship_control_panel_url)"
VM_IP="$(cd terraform/1-deploy-sentinel && terraform output -raw vm_public_ip 2>/dev/null || true)"
VM_USER="$(cd terraform/1-deploy-sentinel && terraform output -raw vm_username 2>/dev/null || true)"
# vm_password is sensitive — `terraform output -raw` returns the literal value.
VM_PASSWORD="$(cd terraform/1-deploy-sentinel && terraform output -raw vm_password 2>/dev/null || true)"

SEP='═════════════════════════════════════════════════════════════════════'
HR='─────────────────────────────────────────────────────────────────────'

printf '\n%s%s%s%s\n'   "$BOLD" "$GREEN" "$SEP" "$NC"
printf '%s%s        AISOC demo deployment complete — everything is live%s\n' \
                       "$BOLD" "$GREEN" "$NC"
printf '%s%s%s%s\n'   "$BOLD" "$GREEN" "$SEP" "$NC"

# ── The two URLs that matter most. Bold cyan so they pop. ──────────────
printf '\n  %sShip Control Panel%s\n' "$BOLD" "$NC"
printf '    %s%s%s%s\n'              "$BOLD" "$CYAN" "$SHIPCP_URL" "$NC"
printf '\n  %sPixelAgents UI%s\n'      "$BOLD" "$NC"
printf '    %s%s%s%s\n'              "$BOLD" "$CYAN" "$PIXEL_URL"  "$NC"

# ── Lab VM details — supporting info, used to seed incidents. ──────────
printf '\n%s%s%s\n'   "$YELLOW" "$HR" "$NC"
printf '  %sLab VM (for seeding incidents)%s\n'  "$BOLD" "$NC"
printf '%s%s%s\n\n'   "$YELLOW" "$HR" "$NC"

[[ -n "$VM_IP"   ]] && printf '  RDP IP:      %s\n' "$VM_IP"
[[ -n "$VM_USER" ]] && printf '  Username:    %s\n' "$VM_USER"
if [[ -n "$VM_PASSWORD" ]]; then
  printf '  Password:    %s%s%s   %s(stable across re-applies)%s\n' \
         "$BOLD" "$VM_PASSWORD" "$NC" "$YELLOW" "$NC"
fi

# ── How to drive the demo. ─────────────────────────────────────────────
printf '\n%sNext steps%s\n' "$BOLD" "$NC"
printf '  1. Open the Ship Control Panel and try a few failed logins, OR\n'
printf '     RDP into the lab VM and try a few bad credentials.\n'
printf '  2. The Sentinel rule fires every 15 min. Once an incident is\n'
printf '     raised, open the PixelAgents UI and click "Run workflow"\n'
printf '     on the incident row to orchestrate triage → investigation\n'
printf '     → reporting.\n'

printf '\n%s%s%s%s\n\n' "$BOLD" "$GREEN" "$SEP" "$NC"
